<a href="https://colab.research.google.com/github/zbigsr814/data-scienice-bootcamp/blob/main/01_wprowadzenie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

In [ ]:
print(dir(np))

Array

In [ ]:
help(np.array)

In [ ]:
x = np.array([1, 3])
type(x)

numpy.ndarray

In [ ]:
x.shape

(2,)

In [ ]:
x.ndim

1

In [ ]:
x.dtype

dtype('int64')

In [ ]:
np.array([3.4, 33.3, 1.09])
print(x)

[1 3]


2D array

In [ ]:
x = np.array([[1,2], [4,5]])
print(x)

[[1 2]
 [4 5]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[2,2,3],[4,3,4]])
print(x)

[[2 2 3]
 [4 3 4]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 3)

3D array

In [ ]:
x = np.array([[[4,4,3],
               [3,3,1]],
              
              [[11,1,3],
               [6,8,9]]])
print(x)

[[[ 4  4  3]
  [ 3  3  1]]

 [[11  1  3]
  [ 6  8  9]]]


In [ ]:
x.shape

(2, 2, 3)

In [ ]:
x.ndim

3

Typy danych

In [ ]:
a = np.array([1.4,6,3], dtype='float')
a.dtype

dtype('float64')

In [ ]:
print(a)

[1.4 6.  3. ]


In [ ]:
a = np.array([True, False])
a.dtype

dtype('bool')

In [ ]:
a = np.array([222,211,21], dtype=np.int8)
a.dtype

dtype('int8')

Tworzenie tablic

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3,5), fill_value=4, dtype='int')

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=55, stop=15, step=-5)

array([55, 50, 45, 40, 35, 30, 25, 20])

In [ ]:
np.arange(start=2, stop=3, step=0.05)

array([2.  , 2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ,
       2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95])

In [ ]:
np.linspace(start=0, stop=2, num=10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [ ]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Operacje na tablicach

In [ ]:
a = np.array([3,4,1,6])
b = np.array([1,9,8,5])
print(a)
print(b)

[3 4 1 6]
[1 9 8 5]


In [ ]:
a+b

array([ 4, 13,  9, 11])

In [ ]:
a/b

array([3.        , 0.44444444, 0.125     , 1.2       ])

In [ ]:
a+3

array([6, 7, 4, 9])

In [ ]:
np.add(a,b)

array([ 4, 13,  9, 11])

In [ ]:
np.subtract(a,b)

array([ 2, -5, -7,  1])

In [ ]:
x = np.array([[2,1], [4,5]])
y = np.array([[0,1], [5,2]])
print(x)
print(y)

[[2 1]
 [4 5]]
[[0 1]
 [5 2]]


In [ ]:
np.dot(x,y)

array([[ 5,  4],
       [25, 14]])

In [ ]:
x @ y

array([[ 5,  4],
       [25, 14]])

In [ ]:
x.dot(y)

array([[ 5,  4],
       [25, 14]])

Liczby losowe

In [ ]:
np.random.randn(3)

array([ 0.64223489, -0.4589396 , -0.61783287])

In [ ]:
np.random.randn(3,2)

array([[ 0.89715732, -0.56659796],
       [ 2.18610821,  0.84412129],
       [ 0.0352862 ,  2.73116142]])

In [ ]:
np.random.randint(low=10, high=101, size=4)

array([50, 10, 52, 89])

In [ ]:
np.random.choice([4,3,7,6])

3

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([9, 6, 3, 8, 5, 4, 1, 0, 2, 7])

Funkcje

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(4)

2.0

In [ ]:
np.all([0,3,1])

False

In [ ]:
np.any([0,0])

False

In [ ]:
bool(5)

True

In [ ]:
a = np.random.randn(5)
a

array([0.42040653, 0.23032023, 1.03311019, 0.78464418, 0.78543764])

In [ ]:
np.argmax(a)

2

In [ ]:
np.argmin(a)

1

In [ ]:
np.argsort(a)

array([1, 0, 3, 4, 2])

In [ ]:
np.max(a)

1.0331101877088145

In [ ]:
np.mean(a)

0.6507837538452408

Indeksowanie, wycinanie

In [ ]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a[3:8]

array([3, 4, 5, 6, 7])

In [ ]:
a[:4]

array([0, 1, 2, 3])

In [ ]:
a = a.reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a[1:3, 1:4]

array([[ 6,  7],
       [11, 12]])

In [ ]:
a[1,3] = 9
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  9,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [ ]:
for row in a:
  print(row)

[0 1 2 3 4]
[5 6 7 9 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in a:
  print(row[:2])

[0 1]
[5 6]
[10 11]
[15 16]


In [ ]:
for item in a.flat:
  print(item)

0
1
2
3
4
5
6
7
9
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
a.shape

(4, 5)

In [ ]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 9,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  9,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  9, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [ ]:
a = np.arange(start=-10, stop=10, step=0.5)
a = a.reshape(10, -1)
a

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
a > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[a > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.bitwise_and(a<2, a>-3)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])