<a href="https://colab.research.google.com/github/zbigsr814/data-scienice-bootcamp/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Wektory

In [2]:
import numpy as np
v1 = np.array([-1, 4])
np.linalg.norm(v1)

4.123105625617661

In [3]:
v2 = np.array([2,4,6])
np.linalg.norm(v2)

7.483314773547883

In [5]:
p = np.array([1,3])
q = np.array([1,4])
np.linalg.norm(p - q)

1.0

Mnożenie macierzy

In [11]:
a = np.array([[3,4],[1,2]])
b = np.array([[2],[3]])
x = np.dot(a,b)
print(x)

[[18]
 [ 8]]


Wyznacznik macierzy

In [12]:
A = np.array([[2,1],[3,4]])
np.linalg.det(A)

5.000000000000001

Ślad macierzy

In [13]:
A = np.array([[2,1],[3,4]])
np.trace(A)

6

Macierz jednostkowa

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

M odwrotna

In [16]:
A = np.array([[2,1],[3,4]])
B = np.linalg.inv(A)
B

array([[ 0.8, -0.2],
       [-0.6,  0.4]])

In [18]:
A.T

array([[2, 3],
       [1, 4]])

In [21]:
A = np.array([[2,4],[1,-1]])
B = np.array([[10],[-1]])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print(X)

[[1.]
 [2.]]
