<a href="https://colab.research.google.com/github/zbigsr814/data-scienice-bootcamp/blob/main/03_funkcje_statyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
A = np.array([[33,3,0.2],
              [34,9,1.2],
              [35,7,0.5],
              [36,4,0.3]])
print(A)

[[33.   3.   0.2]
 [34.   9.   1.2]
 [35.   7.   0.5]
 [36.   4.   0.3]]


In [8]:
np.sum(A, axis=0)

array([138. ,  23. ,   2.2])

In [9]:
np.min(A, axis=0)

array([33. ,  3. ,  0.2])

In [11]:
np.median(A, axis=0)

array([34.5,  5.5,  0.4])

In [12]:
np.std(A, axis=0)

array([1.11803399, 2.384848  , 0.39051248])

In [13]:
np.var(A, axis=0)

array([1.25  , 5.6875, 0.1525])